- name: "Resizing ASG"
  hosts: localhost
  gather_facts: false

  tasks:
  - name: "Set auto-scaling group size to 1"
    ec2_asg:
      name: "minecraft"
      desired_capacity: 1
      region: "{{aws_region}}"
